---
name: Run actionlint and set annotations
description: Run actionlint and set annotations.

inputs:
  ### Flags for actionlint ###
  actionlint_version:
    description: "The version of actionlint to install"
    default: "latest"
    required: false
  actionlint_config:
    description: "Config file to pass to the actionlint command"
    required: false
    default: ""
  file_pattern:
    description: "Files to lint"
    required: false
    default: "."

runs:
  using: "composite"

  steps:
    - name: Register problem matcher
      shell: bash
      run: |
        cp "$GITHUB_ACTION_PATH/src/matcher.json" "actionlint-matcher.json"
        echo "::add-matcher::actionlint-matcher.json"

    - name: Run actionlint
      run: $GITHUB_ACTION_PATH/src/script.sh
      shell: bash
      env:
        ACTIONLINT_VERSION: ${{ inputs.actionlint_version }}
        ACTIONLINT_CONFIG: ${{ inputs.actionlint_config }}
        FILE_PATTERN: ${{ inputs.file_pattern }}
